#!/usr/bin/env python3
"""
Generates a Mermaid architecture diagram from the bootstrap config.

Reads .claude/bootstrap-config.json and produces a Mermaid diagram
showing the system's components and their relationships.

Usage:
    python generate_diagram.py [path/to/.claude/bootstrap-config.json]
    python generate_diagram.py  # defaults to ./.claude/bootstrap-config.json

Output:
    Writes diagram to docs/architecture-diagram.mmd (Mermaid format)
    Also prints the diagram to stdout for easy copy-paste.
"""

import json
import sys
from pathlib import Path


def generate_monolith_diagram(config: dict) -> str:
    """Generate a Mermaid diagram for a monolith architecture."""
    frontend = config.get("frontend", "none")
    backend = config.get("backend", "none")
    database = config.get("database", "none")
    auth = config.get("auth", "none")
    storage = config.get("storage", "none")
    ai = config.get("ai_enabled", False)

    lines = [
        "graph TB",
        "    %% Auto-generated by claude-bootstrap",
        f"    %% Project: {config.get('project_name', 'Unknown')}",
        "",
        "    subgraph Client",
        "        Browser[\"🌐 Browser\"]",
    ]

    # Mobile if configured
    if config.get("mobile_framework"):
        lines.append(f"        Mobile[\"📱 Mobile App\"]")

    lines.extend([
        "    end",
        "",
    ])

    # Frontend/Backend combined or separate
    if frontend != "none" and backend in ("integrated", "none"):
        # Full-stack framework (Next.js, SvelteKit, etc.)
        framework_names = {
            "nextjs": "Next.js",
            "sveltekit": "SvelteKit",
            "nuxt": "Nuxt",
        }
        fw_name = framework_names.get(frontend, frontend.title())

        lines.extend([
            f"    subgraph Application[\"{fw_name} Application\"]",
            "        Frontend[\"🎨 Frontend\\n(SSR + Client)\"]",
            "        API[\"⚡ API Routes\"]",
            "        ServerActions[\"🔧 Server Actions\"]",
            "    end",
        ])
    else:
        # Separate frontend and backend
        if frontend != "none":
            fw_names = {
                "react-vite": "React + Vite",
                "vue": "Vue 3",
                "nextjs": "Next.js",
                "sveltekit": "SvelteKit",
            }
            fw_name = fw_names.get(frontend, frontend.title())
            lines.extend([
                f"    subgraph Frontend[\"{fw_name} Frontend\"]",
                "        UI[\"🎨 UI Components\"]",
                "        State[\"📦 State Management\"]",
                "    end",
                "",
            ])

        if backend not in ("none", "integrated"):
            be_names = {
                "node-express": "Node.js / Express",
                "node-fastify": "Node.js / Fastify",
                "python-fastapi": "Python / FastAPI",
                "python-django": "Python / Django",
                "go": "Go",
            }
            be_name = be_names.get(backend, backend.title())
            lines.extend([
                f"    subgraph Backend[\"{be_name} Backend\"]",
                "        API[\"⚡ API Layer\"]",
                "        Services[\"🔧 Business Logic\"]",
                "        Repos[\"💾 Data Access\"]",
                "    end",
                "",
            ])

    # Auth
    if auth != "none":
        auth_names = {
            "clerk": "Clerk",
            "nextauth": "Auth.js",
            "supabase-auth": "Supabase Auth",
            "custom-jwt": "Custom JWT",
        }
        auth_name = auth_names.get(auth, auth.title())
        lines.append(f"    Auth[\"🔐 {auth_name}\"]")
        lines.append("")

    # Database
    if database != "none":
        db_names = {
            "postgresql": "PostgreSQL",
            "mongodb": "MongoDB",
            "supabase": "Supabase (PostgreSQL)",
            "dynamodb": "DynamoDB",
            "sqlite": "SQLite",
            "mysql": "MySQL",
        }
        db_name = db_names.get(database, database.title())
        lines.append(f"    DB[(\"🗄️ {db_name}\")]")
        lines.append("")

    # Storage
    if storage != "none":
        storage_names = {
            "s3": "AWS S3",
            "r2": "Cloudflare R2",
            "minio": "MinIO",
            "supabase-storage": "Supabase Storage",
            "uploadthing": "UploadThing",
        }
        s_name = storage_names.get(storage, storage.title())
        lines.append(f"    Storage[\"📁 {s_name}\"]")
        lines.append("")

    # AI
    if ai:
        ai_provider = config.get("ai_provider", "Claude API")
        lines.append(f"    AI[\"🤖 {ai_provider}\"]")
        lines.append("")

    # Cache
    if config.get("cache"):
        lines.append("    Cache[\"⚡ Redis Cache\"]")
        lines.append("")

    # ── Connections ────────────────────────────────────────────
    lines.append("    %% Connections")

    if frontend != "none" and backend in ("integrated", "none"):
        lines.append("    Browser --> Frontend")
        lines.append("    Browser --> API")
        if auth != "none":
            lines.append("    API --> Auth")
        if database != "none":
            lines.append("    ServerActions --> DB")
            lines.append("    API --> DB")
        if storage != "none":
            lines.append("    API --> Storage")
            lines.append("    Browser -.->|\"presigned URL\"| Storage")
        if ai:
            lines.append("    API --> AI")
    else:
        if frontend != "none":
            lines.append("    Browser --> UI")
        if backend not in ("none", "integrated"):
            if frontend != "none":
                lines.append("    UI --> API")
            else:
                lines.append("    Browser --> API")
            lines.append("    API --> Services")
            lines.append("    Services --> Repos")
            if auth != "none":
                lines.append("    API --> Auth")
            if database != "none":
                lines.append("    Repos --> DB")
            if storage != "none":
                lines.append("    Services --> Storage")
            if ai:
                lines.append("    Services --> AI")

    if config.get("cache"):
        lines.append("    Services --> Cache")

    if config.get("mobile_framework"):
        lines.append("    Mobile --> API")

    # Styling
    lines.extend([
        "",
        "    %% Styling",
        "    classDef frontend fill:#4CAF50,stroke:#333,color:#fff",
        "    classDef backend fill:#2196F3,stroke:#333,color:#fff",
        "    classDef database fill:#FF9800,stroke:#333,color:#fff",
        "    classDef external fill:#9C27B0,stroke:#333,color:#fff",
    ])

    return "\n".join(lines)


def generate_microservices_diagram(config: dict) -> str:
    """Generate a Mermaid diagram for a microservices architecture."""
    lines = [
        "graph TB",
        f"    %% Auto-generated by claude-bootstrap",
        f"    %% Project: {config.get('project_name', 'Unknown')}",
        "",
        "    Client[\"🌐 Client\"]",
        "    Gateway[\"🚪 API Gateway\"]",
        "",
        "    subgraph Services",
        "        UserSvc[\"👤 User Service\"]",
        "        CoreSvc[\"⚙️ Core Service\"]",
        "        NotifSvc[\"📧 Notification Service\"]",
        "    end",
        "",
        "    subgraph Data",
    ]

    database = config.get("database", "postgresql")
    db_name = {"postgresql": "PostgreSQL", "mongodb": "MongoDB", "dynamodb": "DynamoDB"}.get(database, database)
    lines.extend([
        f"        UserDB[(\"🗄️ User {db_name}\")]",
        f"        CoreDB[(\"🗄️ Core {db_name}\")]",
        "    end",
        "",
        "    Queue[\"📬 Message Queue\"]",
        "",
        "    Client --> Gateway",
        "    Gateway --> UserSvc",
        "    Gateway --> CoreSvc",
        "    UserSvc --> UserDB",
        "    CoreSvc --> CoreDB",
        "    CoreSvc --> Queue",
        "    Queue --> NotifSvc",
    ])

    return "\n".join(lines)


def main():
    config_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".claude/bootstrap-config.json")

    if not config_path.exists():
        print(f"❌ Config not found: {config_path}")
        print("Run the scaffold script first to generate bootstrap-config.json")
        sys.exit(1)

    config = json.loads(config_path.read_text())
    arch = config.get("architecture", "monolith")

    if arch == "microservices":
        diagram = generate_microservices_diagram(config)
    else:
        diagram = generate_monolith_diagram(config)

    # Write to file
    output_dir = config_path.parent.parent / "docs"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / "architecture-diagram.mmd"
    output_file.write_text(diagram + "\n")

    print(f"✅ Diagram written to {output_file}")
    print(f"\nTo render: paste into https://mermaid.live or use in markdown:\n")
    print("```mermaid")
    print(diagram)
    print("```")


if __name__ == "__main__":
    main()
